language: python
python:
  - "2.7"
install:
  - pip install tornado
  - pip install pymongo
  - pip install mongomock
script:
  - nosetests --with-coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
